name: Request Unity Activation File
on: workflow_dispatch
jobs:
  activation:
    name: Request Unity Activation File
    runs-on: ubuntu-latest
    steps:
      - name: Request Unity Activation File
        id: request
        uses: game-ci/unity-request-activation-file@v2
        
      - name: Upload Artifact
        id: artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.request.outputs.filePath }}
          path: ${{ steps.request.outputs.filePath }}
    
      - name: Finished
        run: echo "Convert your activation file into a license file at https://license.unity3d.com/manual"
