name: Build
on: 
  workflow_dispatch:
  push:
    branches:
    - stable
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    environment: production
    permissions: write-all
    env:
      projectName: Spellbound
    strategy:
        matrix:
          targetPlatform:
            - WebGL
    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: stable
          fetch-depth: 0
        
      - name: Cache Repository
        id: cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      
      - name: Version
        id: version
        uses: paulhatch/semantic-version@v5.0.3
        with:
          tag_prefix: ''
          version_format: "${major}.${minor}.${increment}"
          bump_each_commit: true
      
      - name: Build Project
        id: build
        uses: game-ci/unity-builder@v2.1.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: ${{ env.projectName }}
          versioning: Custom
          version: ${{ steps.version.outputs.version_tag }}
          customParameters: -Development
          
      - name: Create Artifact for GitHub Pages
        id: artifact
        uses: actions/upload-pages-artifact@v1.0.8
        if: matrix.targetPlatform == 'WebGL'
        with:
          path: build/${{ matrix.targetPlatform }}/${{ env.projectName }}/
          
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2.0.0
        if: matrix.targetPlatform == 'WebGL'
        
      - name: Add Tag to Commit
        id: tag
        uses: rickstaa/action-create-tag@v1.6.1
        with:
          tag: ${{ steps.version.outputs.version_tag }}
